### ISSUE TITLE
data downloading issue

### ISSUE THREAD

**Issue by ch3cook-fdu** [UncleMEDM/Refer-it-in-RGBD#1]
Could you upload and share the dataset through baiducloud? the downloading speed of office365 cloud is slow while unstable.

**Comment by HaolinLiu97** [comment]
I will upload it onto baiducloud ASAP.

**Comment by HaolinLiu97** [comment]
The BaiduCloud link is already updated.

**Comment by ch3cook-fdu** [comment]
that helps a lot! thanks!
